# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_task', '0003_document_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='day_task',
            name='tasks',
            field=models.ManyToManyField(null=True, to='event_task.Task'),
        ),
    ]
